//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public int price { get; set; }
        public int status { get; set; }
        public int id_bill { get; set; }
        public int id_scheduletime { get; set; }
        public string seat { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual ScheduleTime ScheduleTime { get; set; }
    }
}
